#!/usr/bin/env bash
#
if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /tmp/my_process.pid
    echo "$!" > /tmp/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /tmp/my_process.pid)"
    rm -rf  /tmp/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm -rf /tmp/my_process.pid
    ./manage_my_process &
    touch /tmp/my_process.pid
    echo "$!" > /tmp/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
